/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-116756-gcfe0a36352-20240823"
#endif /* AVUTIL_FFVERSION_H */
